-- Run once in the Supabase SQL Editor (Dashboard > SQL Editor) for project
-- wmofflwywrivbkuqyfif. Adds the Service UAQ fields used by serviceuaq.html.
-- Safe to re-run: each statement only adds a column if it does not exist yet.

alter table public.boss_cars_uaq add column if not exists service_date text;
alter table public.boss_cars_uaq add column if not exists service_mileage text;
alter table public.boss_cars_uaq add column if not exists service_mileage_ask_rinat text;
alter table public.boss_cars_uaq add column if not exists service_mileage_after text;
alter table public.boss_cars_uaq add column if not exists service_tires text;
alter table public.boss_cars_uaq add column if not exists service_work text;

-- -----------------------------------------------------------------------------
-- Mr AK Cars registrations (mrakcars.html + vehicles.html + dashboard summary)
-- Run this section once. Safe to re-run.
-- -----------------------------------------------------------------------------

create table if not exists public.mr_ak_cars (
	id bigint generated by default as identity primary key,
	brand text not null,
	year text,
	code text not null,
	plate text not null,
	chassis text,
	expiry date,
	photo text,
	maintenance text,
	created_at timestamptz not null default now()
);

-- Allow the team (anon key) to read and write records from the browser.
do $$
begin
	if not exists (
		select 1 from pg_policies
		where tablename = 'mr_ak_cars' and policyname = 'team full access'
	) then
		create policy "team full access" on public.mr_ak_cars
			for all to anon using (true) with check (true);
	end if;
end
$$;

-- Reminder: Row Level Security must allow anon read for the team to see these
-- records in the browser. Section 3 below sets read-for-everyone + write-for-
-- admin-only policies on all three tables.

-- =============================================================================
-- 3. VIEWER / ADMIN ROLES (run once — this is what enforces "only the boss can
--    edit"). Safe to re-run.
--
--    Login model (auth-gate.js):
--      * Team password (viewers): checked in the browser, read-only.
--      * Admin password: verified here against its SHA-256 hash; the browser
--        keeps the token and sends it on every request as x-ak-admin-token.
--    The policies below REJECT insert/update/delete from any request without a
--    valid token — so browser DevTools cannot bypass it.
-- =============================================================================

-- Config table: stores the admin password hash (and flags the setup as done).
create table if not exists public.app_config (
	key text primary key,
	value text not null
);

-- The hash must not be readable by the public anon role (a 6-digit password's
-- hash can be brute-forced instantly). RLS with no policies = deny all.
alter table public.app_config enable row level security;

-- Store SHA-256('060720') as the admin password hash. Re-run this line anytime
-- you want to change the admin password (replace the hash):
--   select sha256(convert_to('NEW_PASSWORD', 'utf8'));
insert into public.app_config (key, value)
values
	('admin_password_sha256', '6b4cb38283006994a72c3bcb8ca2e8808e18e0556a87f841d382d671662a0589'),
	('admin_token_sha256', '6b4cb38283006994a72c3bcb8ca2e8808e18e0556a87f841d382d671662a0589')
on conflict (key) do update set value = excluded.value;

-- Login check: returns true only when the password matches the stored hash.
-- Anyone can call it (it is a login form), but it reveals nothing else.
create or replace function public.check_admin_password(candidate text)
returns boolean
language sql
security definer
set search_path = public
as $$
	select exists (
		select 1 from public.app_config
		where key = 'admin_password_sha256'
		  and value = encode(sha256(convert_to(coalesce(candidate, ''), 'utf8')), 'hex')
	);
$$;

grant execute on function public.check_admin_password(text) to anon;
grant select on public.app_config to anon;

-- Every write must present the admin token; readers need nothing.
-- security definer + owned-by-postgres: this function must read app_config even
-- though RLS denies the anon role (otherwise admin writes would fail too).
create or replace function public.is_ak_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
	select exists (
		select 1 from public.app_config
		where key = 'admin_token_sha256'
		  and value = coalesce(
				nullif(current_setting('request.headers', true)::json ->> 'x-ak-admin-token', ''),
				''
		  )
	);
$$;

-- Replace ALL existing policies on the three tables. Reads stay open for the
-- whole team; writes (insert/update/delete) now require the admin token.
-- Every old policy is dropped by name lookup (not by hardcoded name): policies
-- combine with OR in Postgres, so any leftover open policy would keep the table
-- writable by everyone.
do $$
declare
	t text;
	r record;
begin
	foreach t in array array['mr_ak_cars', 'boss_cars_uaq', 'vip_numbers'] loop
		for r in
			select policyname from pg_policies
			where schemaname = 'public' and tablename = t
				and policyname not in ('team can read', 'admin can insert', 'admin can update', 'admin can delete')
		loop
			execute format('drop policy if exists %I on public.%I', r.policyname, t);
		end loop;
		-- Recreate the four role policies fresh so they bind to the current
		-- is_ak_admin() definition. Safe to re-run.
		execute format('drop policy if exists "team can read" on public.%I', t);
		execute format('create policy "team can read" on public.%I for select to anon using (true)', t);
		execute format('drop policy if exists "admin can insert" on public.%I', t);
		execute format('create policy "admin can insert" on public.%I for insert to anon with check (public.is_ak_admin())', t);
		execute format('drop policy if exists "admin can update" on public.%I', t);
		execute format('create policy "admin can update" on public.%I for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin())', t);
		execute format('drop policy if exists "admin can delete" on public.%I', t);
		execute format('create policy "admin can delete" on public.%I for delete to anon using (public.is_ak_admin())', t);
	end loop;
end
$$;

-- Note: the RPC uses Postgres's built-in sha256(), so no extension is needed.
-- (An earlier draft used pgcrypto's digest(), which is not on the default
-- search path in Supabase — sha256() avoids that entirely.)

-- =============================================================================
-- 4. MR AK CARS SERVICE FIELDS (run once — lets serviceuaq.html?from=mrak show
--    and edit service data for Mr AK Cars records). Safe to re-run.
-- =============================================================================

alter table public.mr_ak_cars add column if not exists service_date text;
alter table public.mr_ak_cars add column if not exists service_mileage text;
alter table public.mr_ak_cars add column if not exists service_mileage_ask_rinat text;
alter table public.mr_ak_cars add column if not exists service_mileage_after text;
alter table public.mr_ak_cars add column if not exists service_tires text;
alter table public.mr_ak_cars add column if not exists service_work text;
alter table public.mr_ak_cars add column if not exists garage_location text;

-- No new policies needed: section 3 already covers mr_ak_cars (team reads,
-- admin writes) — the new columns ride along automatically.

-- =============================================================================
-- 5. MODIFICATIONS BUILD QUEUE (run once — makes project.html live for the
--    whole team). Safe to re-run.
--
--    One row per modification job: car, what is being done, progress %,
--    status (in progress / completed), and notes. Team (viewers) sees the
--    queue; admin adds, edits progress/status, and erases.
-- =============================================================================

create table if not exists public.modifications (
	id uuid primary key default gen_random_uuid(),
	created_at timestamptz not null default now(),
	title text not null,
	description text,
	status text not null default 'In progress',
	progress integer not null default 0 check (progress between 0 and 100),
	car text,
	due_date text
);

-- Excel-format build cards (Car Expenses.xlsx style). Safe to re-run.
alter table public.modifications add column if not exists chassis text;
alter table public.modifications add column if not exists sold_price numeric;
alter table public.modifications add column if not exists grand_total numeric not null default 0;
alter table public.modifications add column if not exists pnl numeric;
alter table public.modifications add column if not exists expenses jsonb not null default '[]'::jsonb;

alter table public.modifications enable row level security;

drop policy if exists "team can read modifications" on public.modifications;
create policy "team can read modifications" on public.modifications
	for select to anon using (true);

drop policy if exists "admin can insert modifications" on public.modifications;
create policy "admin can insert modifications" on public.modifications
	for insert to anon with check (public.is_ak_admin());

drop policy if exists "admin can update modifications" on public.modifications;
create policy "admin can update modifications" on public.modifications
	for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin());

drop policy if exists "admin can delete modifications" on public.modifications;
create policy "admin can delete modifications" on public.modifications
	for delete to anon using (public.is_ak_admin());

-- 6. MOTORCYCLE RECORDS (run once — makes motorcycles.html live for the whole
--    team). Safe to re-run.
--
--    Same shape as mr_ak_cars: one row per motorcycle with brand, year, code,
--    plate, chassis, expiry date and optional photo. Team (viewers) sees the
--    records; admin adds, edits, and erases. Same RLS protection as section 3.
-- =============================================================================

create table if not exists public.motorcycles (
	id uuid primary key default gen_random_uuid(),
	created_at timestamptz not null default now(),
	brand text not null,
	year text,
	code text,
	plate text,
	chassis text,
	expiry date,
	photo text,
	maintenance text
);

alter table public.motorcycles enable row level security;

drop policy if exists "team can read motorcycles" on public.motorcycles;
create policy "team can read motorcycles" on public.motorcycles
	for select to anon using (true);

drop policy if exists "admin can insert motorcycles" on public.motorcycles;
create policy "admin can insert motorcycles" on public.motorcycles
	for insert to anon with check (public.is_ak_admin());

drop policy if exists "admin can update motorcycles" on public.motorcycles;
create policy "admin can update motorcycles" on public.motorcycles
	for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin());

drop policy if exists "admin can delete motorcycles" on public.motorcycles;
create policy "admin can delete motorcycles" on public.motorcycles
	for delete to anon using (public.is_ak_admin());

-- 7. VIP MOTORCYCLE PLATES (run once — makes vipmoto.html live for the whole
--    team). Safe to re-run.
--
--    Same shape as vip_numbers: one row per premium motorcycle plate with
--    code, emirates, plate number and status. Team (viewers) sees the list;
--    admin adds, changes status, and erases. Same RLS protection as section 3.
-- =============================================================================

create table if not exists public.vip_motorcycles (
	id uuid primary key default gen_random_uuid(),
	created_at timestamptz not null default now(),
	code text,
	emirates text,
	plate text,
	status text not null default 'Available'
);

alter table public.vip_motorcycles enable row level security;

drop policy if exists "team can read vip_motorcycles" on public.vip_motorcycles;
create policy "team can read vip_motorcycles" on public.vip_motorcycles
	for select to anon using (true);

drop policy if exists "admin can insert vip_motorcycles" on public.vip_motorcycles;
create policy "admin can insert vip_motorcycles" on public.vip_motorcycles
	for insert to anon with check (public.is_ak_admin());

drop policy if exists "admin can update vip_motorcycles" on public.vip_motorcycles;
create policy "admin can update vip_motorcycles" on public.vip_motorcycles
	for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin());

drop policy if exists "admin can delete vip_motorcycles" on public.vip_motorcycles;
create policy "admin can delete vip_motorcycles" on public.vip_motorcycles
	for delete to anon using (public.is_ak_admin());
