-- Run once in the Supabase SQL Editor (Dashboard > SQL Editor) for project
-- wmofflwywrivbkuqyfif. Adds the Service UAQ fields used by serviceuaq.html.
-- Safe to re-run: each statement only adds a column if it does not exist yet.

alter table public.boss_cars_uaq add column if not exists service_date text;
alter table public.boss_cars_uaq add column if not exists service_mileage text;
alter table public.boss_cars_uaq add column if not exists service_mileage_ask_rinat text;
alter table public.boss_cars_uaq add column if not exists service_mileage_after text;
alter table public.boss_cars_uaq add column if not exists service_tires text;
alter table public.boss_cars_uaq add column if not exists service_work text;

-- -----------------------------------------------------------------------------
-- Mr AK Cars registrations (mrakcars.html + vehicles.html + dashboard summary)
-- Run this section once. Safe to re-run.
-- -----------------------------------------------------------------------------

create table if not exists public.mr_ak_cars (
	id bigint generated by default as identity primary key,
	brand text not null,
	year text,
	code text not null,
	plate text not null,
	chassis text,
	expiry date,
	photo text,
	maintenance text,
	created_at timestamptz not null default now()
);

-- Allow the team (anon key) to read and write records from the browser.
do $$
begin
	if not exists (
		select 1 from pg_policies
		where tablename = 'mr_ak_cars' and policyname = 'team full access'
	) then
		create policy "team full access" on public.mr_ak_cars
			for all to anon using (true) with check (true);
	end if;
end
$$;

-- Reminder: Row Level Security must allow anon read for the team to see these
-- records in the browser. Section 3 below sets read-for-everyone + write-for-
-- admin-only policies on all three tables.

-- =============================================================================
-- 3. VIEWER / ADMIN ROLES (run once — this is what enforces "only the boss can
--    edit"). Safe to re-run.
--
--    Login model (auth-gate.js):
--      * Team password (viewers): checked in the browser, read-only.
--      * Admin password: verified here against its SHA-256 hash; the browser
--        keeps the token and sends it on every request as x-ak-admin-token.
--    The policies below REJECT insert/update/delete from any request without a
--    valid token — so browser DevTools cannot bypass it.
-- =============================================================================

-- Config table: stores only the admin password hash. No credential or bearer
-- token is seeded in this public migration file.
create table if not exists public.app_config (
	key text primary key,
	value text not null
);

-- Config and session rows are available only to these SECURITY DEFINER
-- functions. RLS with no policies denies direct anon access.
alter table public.app_config enable row level security;
insert into public.app_config (key, value)
values ('admin_password_sha256', '')
on conflict (key) do nothing;

-- Disable the previously published password/token hash on existing installs.
update public.app_config
set value = ''
where key = 'admin_password_sha256'
  and value = '6b4cb38283006994a72c3bcb8ca2e8808e18e0556a87f841d382d671662a0589';
delete from public.app_config where key = 'admin_token_sha256';

create table if not exists public.admin_sessions (
	token_hash text primary key,
	expires_at timestamptz not null
);
alter table public.admin_sessions enable row level security;
revoke all on public.admin_sessions from public, anon, authenticated;
revoke all on public.app_config from public, anon, authenticated;

-- Login issues a random opaque session token; only its hash is stored.
-- Password hashing uses SHA-256 because the configured password must be
-- generated from at least 32 random bytes (see README setup instructions).
drop function if exists public.check_admin_password(text);
create or replace function public.login_admin(candidate text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
	stored_hash text;
	session_token text;
begin
	select value into stored_hash
	from public.app_config
	where key = 'admin_password_sha256';

	if stored_hash is null
		or stored_hash = ''
		or stored_hash <> encode(sha256(convert_to(coalesce(candidate, ''), 'utf8')), 'hex') then
		return null;
	end if;

	session_token := replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
	delete from public.admin_sessions where expires_at <= now();
	insert into public.admin_sessions (token_hash, expires_at)
	values (encode(sha256(convert_to(session_token, 'utf8')), 'hex'), now() + interval '30 days');
	return session_token;
end;
$$;

revoke all on function public.login_admin(text) from public, authenticated;
grant execute on function public.login_admin(text) to anon;

-- Every write must present the admin token; readers need nothing.
-- The raw token is never stored in the database or source repository.
create or replace function public.is_ak_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
	select exists (
		select 1
		from public.admin_sessions
		where token_hash = encode(
			sha256(convert_to(coalesce(
				nullif(current_setting('request.headers', true)::json ->> 'x-ak-admin-token', ''),
				''
			), 'utf8')),
			'hex'
		)
		  and expires_at > now()
	);
$$;

revoke all on function public.is_ak_admin() from public, authenticated;
grant execute on function public.is_ak_admin() to anon;

-- Replace ALL existing policies on the three tables. Reads stay open for the
-- whole team; writes (insert/update/delete) now require the admin token.
-- Every old policy is dropped by name lookup (not by hardcoded name): policies
-- combine with OR in Postgres, so any leftover open policy would keep the table
-- writable by everyone.
do $$
declare
	t text;
	r record;
begin
	foreach t in array array['mr_ak_cars', 'boss_cars_uaq', 'vip_numbers'] loop
		for r in
			select policyname from pg_policies
			where schemaname = 'public' and tablename = t
				and policyname not in ('team can read', 'admin can insert', 'admin can update', 'admin can delete')
		loop
			execute format('drop policy if exists %I on public.%I', r.policyname, t);
		end loop;
		-- Recreate the four role policies fresh so they bind to the current
		-- is_ak_admin() definition. Safe to re-run.
		execute format('drop policy if exists "team can read" on public.%I', t);
		execute format('create policy "team can read" on public.%I for select to anon using (true)', t);
		execute format('drop policy if exists "admin can insert" on public.%I', t);
		execute format('create policy "admin can insert" on public.%I for insert to anon with check (public.is_ak_admin())', t);
		execute format('drop policy if exists "admin can update" on public.%I', t);
		execute format('create policy "admin can update" on public.%I for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin())', t);
		execute format('drop policy if exists "admin can delete" on public.%I', t);
		execute format('create policy "admin can delete" on public.%I for delete to anon using (public.is_ak_admin())', t);
	end loop;
end
$$;

-- Note: the RPC uses Postgres's built-in sha256(), so no extension is needed.
-- (An earlier draft used pgcrypto's digest(), which is not on the default
-- search path in Supabase — sha256() avoids that entirely.)

-- =============================================================================
-- 4. MR AK CARS SERVICE FIELDS (run once — lets serviceuaq.html?from=mrak show
--    and edit service data for Mr AK Cars records). Safe to re-run.
-- =============================================================================

alter table public.mr_ak_cars add column if not exists service_date text;
alter table public.mr_ak_cars add column if not exists service_mileage text;
alter table public.mr_ak_cars add column if not exists service_mileage_ask_rinat text;
alter table public.mr_ak_cars add column if not exists service_mileage_after text;
alter table public.mr_ak_cars add column if not exists service_tires text;
alter table public.mr_ak_cars add column if not exists service_work text;
alter table public.mr_ak_cars add column if not exists garage_location text;

-- No new policies needed: section 3 already covers mr_ak_cars (team reads,
-- admin writes) — the new columns ride along automatically.

-- =============================================================================
-- 5. MODIFICATIONS BUILD QUEUE (run once — makes project.html live for the
--    whole team). Safe to re-run.
--
--    One row per modification job: car, what is being done, progress %,
--    status (in progress / completed), and notes. Team (viewers) sees the
--    queue; admin adds, edits progress/status, and erases.
-- =============================================================================

create table if not exists public.modifications (
	id uuid primary key default gen_random_uuid(),
	created_at timestamptz not null default now(),
	title text not null,
	description text,
	status text not null default 'In progress',
	progress integer not null default 0 check (progress between 0 and 100),
	car text,
	due_date text
);

-- Excel-format build cards (Car Expenses.xlsx style). Safe to re-run.
alter table public.modifications add column if not exists chassis text;
alter table public.modifications add column if not exists sold_price numeric;
alter table public.modifications add column if not exists grand_total numeric not null default 0;
alter table public.modifications add column if not exists pnl numeric;
alter table public.modifications add column if not exists expenses jsonb not null default '[]'::jsonb;

alter table public.modifications enable row level security;

drop policy if exists "team can read modifications" on public.modifications;
create policy "team can read modifications" on public.modifications
	for select to anon using (true);

drop policy if exists "admin can insert modifications" on public.modifications;
create policy "admin can insert modifications" on public.modifications
	for insert to anon with check (public.is_ak_admin());

drop policy if exists "admin can update modifications" on public.modifications;
create policy "admin can update modifications" on public.modifications
	for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin());

drop policy if exists "admin can delete modifications" on public.modifications;
create policy "admin can delete modifications" on public.modifications
	for delete to anon using (public.is_ak_admin());

-- 6. MOTORCYCLE RECORDS (run once — makes motorcycles.html live for the whole
--    team). Safe to re-run.
--
--    Same shape as mr_ak_cars: one row per motorcycle with brand, year, code,
--    plate, chassis, expiry date and optional photo. Team (viewers) sees the
--    records; admin adds, edits, and erases. Same RLS protection as section 3.
-- =============================================================================

create table if not exists public.motorcycles (
	id uuid primary key default gen_random_uuid(),
	created_at timestamptz not null default now(),
	brand text not null,
	year text,
	code text,
	plate text,
	chassis text,
	expiry date,
	photo text,
	maintenance text
);

alter table public.motorcycles enable row level security;

drop policy if exists "team can read motorcycles" on public.motorcycles;
create policy "team can read motorcycles" on public.motorcycles
	for select to anon using (true);

drop policy if exists "admin can insert motorcycles" on public.motorcycles;
create policy "admin can insert motorcycles" on public.motorcycles
	for insert to anon with check (public.is_ak_admin());

drop policy if exists "admin can update motorcycles" on public.motorcycles;
create policy "admin can update motorcycles" on public.motorcycles
	for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin());

drop policy if exists "admin can delete motorcycles" on public.motorcycles;
create policy "admin can delete motorcycles" on public.motorcycles
	for delete to anon using (public.is_ak_admin());

-- 7. VIP MOTORCYCLE PLATES (run once — makes vipmoto.html live for the whole
--    team). Safe to re-run.
--
--    Same shape as vip_numbers: one row per premium motorcycle plate with
--    code, emirates, plate number and status. Team (viewers) sees the list;
--    admin adds, changes status, and erases. Same RLS protection as section 3.
-- =============================================================================

create table if not exists public.vip_motorcycles (
	id uuid primary key default gen_random_uuid(),
	created_at timestamptz not null default now(),
	code text,
	emirates text,
	plate text,
	status text not null default 'Available'
);

alter table public.vip_motorcycles enable row level security;

drop policy if exists "team can read vip_motorcycles" on public.vip_motorcycles;
create policy "team can read vip_motorcycles" on public.vip_motorcycles
	for select to anon using (true);

drop policy if exists "admin can insert vip_motorcycles" on public.vip_motorcycles;
create policy "admin can insert vip_motorcycles" on public.vip_motorcycles
	for insert to anon with check (public.is_ak_admin());

drop policy if exists "admin can update vip_motorcycles" on public.vip_motorcycles;
create policy "admin can update vip_motorcycles" on public.vip_motorcycles
	for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin());

drop policy if exists "admin can delete vip_motorcycles" on public.vip_motorcycles;
create policy "admin can delete vip_motorcycles" on public.vip_motorcycles
	for delete to anon using (public.is_ak_admin());

-- =============================================================================
-- 8. MAINTENANCE CHECKLIST (run once — makes maintenance.html live for the
--    whole team). Safe to re-run.
--
--    One row = one full maintenance checklist for one vehicle visit.
--    items / notes / photos / gen_photos are JSONB so the page can store the
--    whole checklist (Done / OK / Attn marks, per-item notes, compressed
--    photos as data URLs) without extra tables.
-- =============================================================================

create table if not exists public.maintenance_checks (
	id uuid primary key default gen_random_uuid(),
	created_at timestamptz not null default now(),
	updated_at timestamptz,
	plate text not null,
	model text not null default '',
	service_date text not null default '',
	km bigint not null default 0,
	mechanic text not null default '',
	location text not null default '',
	cost numeric not null default 0,
	next_km bigint not null default 0,
	remarks text not null default '',
	items jsonb not null default '{}'::jsonb,
	notes jsonb not null default '{}'::jsonb,
	photos jsonb not null default '{}'::jsonb,
	gen_photos jsonb not null default '[]'::jsonb
);

alter table public.maintenance_checks enable row level security;

drop policy if exists "team can read maintenance_checks" on public.maintenance_checks;
create policy "team can read maintenance_checks" on public.maintenance_checks
	for select to anon using (true);

drop policy if exists "admin can insert maintenance_checks" on public.maintenance_checks;
create policy "admin can insert maintenance_checks" on public.maintenance_checks
	for insert to anon with check (public.is_ak_admin());

drop policy if exists "admin can update maintenance_checks" on public.maintenance_checks;
create policy "admin can update maintenance_checks" on public.maintenance_checks
	for update to anon using (public.is_ak_admin()) with check (public.is_ak_admin());

drop policy if exists "admin can delete maintenance_checks" on public.maintenance_checks;
create policy "admin can delete maintenance_checks" on public.maintenance_checks
	for delete to anon using (public.is_ak_admin());
